### ISSUE TITLE
How is this project licensed?

### ISSUE THREAD

**Issue by robertodr** [vahtras/daltools#3]
For context: I am trying to publish this package on conda-forge using [grayskull](https://github.com/conda-incubator/grayskull). Since the project has no license, the tool cannot find it and rightfully complains.

**Comment by vahtras** [comment]
Great! I started fiddling with conda-forge some time ago, but lost steam... just added one

**Comment by robertodr** [comment]
Thanks! Could you also mint a new release on PyPI too?

Eh, it can be intense to get it to work, the documentation is a bit diffuse... I've had some success with XCFun, MRCPP, and MRChem lately (after a year-long struggle) Drop me a note if you have any questions on the packaging process.

**Comment by vahtras** [comment]
Sorry about delay, but now a new version on pypi. It would be great if you
can document your conda process on e.g. Trello in the "useful notes" column
